### ISSUE TITLE
Trying to make the cheat work with my limited knowledge 

### ISSUE THREAD

**Issue by ZeroRzv** [Coopyy/EgguWare-Unturned#4]
Hi, I managed to compile the hack "as is" but I am not sure if it is still working for the newest update, it doesn't work for me, Unturned won't start at all.
Tried your other hack Binjector but didn't succeed with that either
I just want to ask you, the dev, if the hack works in this update because I want to know if I gotta try to rewrite some of it or if I just got some references wrong or something.
Also, do I have to use an Injector, or do I just copy the DLL's and assets? (I had a hack some time ago that had that method and would just start)

**Comment by ZeroRzv** [comment]
Also, looking at the source is /Unturned_Data/GUISkins/ supposed to be there already, or is the hack supposed to make that dir... sorry if I am asking stupid questions

**Comment by Coopyy** [comment]
sorry this is late i dont check this often

id recommend checking the games logs in `AppData\LocalLow\Smartly Dressed Games\Unturned\output_log.txt` to see what you might have to change with the cheat. im assuming something with the overrides has to be changed

how you want to load it is up to you, you can use a mono injector if youre playing with battleye disabled, otherwise i cant help much there

the gui skins folder is made by the cheat

**Comment by Coopyy** [comment]
id also recommend replacing the files in the references folder with the ones in Unturned's managed folder
